### ISSUE TITLE
"No Found" error message on the page

### ISSUE THREAD

**Issue by tolatolatop** [lark-parser/ide#4]
The request return 404 but I don’t know what’s missing

Start the program with the following configuration
````
$ npm -v
8.1.4
$ node -v
v17.2.0
$ cat package-lock.json | grep @svel
        "@sveltejs/adapter-static": "^1.0.0-next.15",
        "@sveltejs/kit": "next",
    "node_modules/@sveltejs/adapter-static": {
    "node_modules/@sveltejs/kit": {
      "resolved": "https://registry.npmjs.org/@sveltejs/kit/-/kit-1.0.0-next.201.tgz",
        "@sveltejs/vite-plugin-svelte": "^1.0.0-next.30",
    "node_modules/@sveltejs/vite-plugin-svelte": {
    "@sveltejs/adapter-static": {
    "@sveltejs/kit": {
      "resolved": "https://registry.npmjs.org/@sveltejs/kit/-/kit-1.0.0-next.201.tgz",
        "@sveltejs/vite-plugin-svelte": "^1.0.0-next.30",
    "@sveltejs/vite-plugin-svelte": 
````
error message on page
````
Error: Not found:
    at resolve (file:///root/project/ide/node_modules/@sveltejs/kit/dist/ssr.js:1754:13)
    at async Object.handle (/root/project/ide/src/hooks.ts:14:24)
    at async respond (file:///root/project/ide/node_modules/@sveltejs/kit/dist/ssr.js:1696:10)
    at async svelteKitMiddleware (file:///root/project/ide/node_modules/@sveltejs/kit/dist/chunks/index.js:4557:22)
````
![image](https://user-images.githubusercontent.com/43093785/144439155-0983e43f-f5ca-47cd-bcb9-7eb3622eccce.png)

log on server
````
10:16:22 PM [vite-plugin-svelte] /root/project/ide/src/routes/__layout.svelte:34:3 A11y: <a> element should have an href attribute
````

**Comment by erezsh** [comment]
Are you getting this from running locally or from accessing lark-parser.org?

**Comment by tolatolatop** [comment]
locally. I can access lark-parser.org normally.

**Comment by erezsh** [comment]
So, I need some more info. 

Are you using `npm run dev`?

**Comment by tolatolatop** [comment]
yes
I started the service through the following steps.
````
git clone https://github.com/lark-parser/ide.git
cd ide
npm install 
npm run dev
# all on root
````

**Comment by erezsh** [comment]
Maybe try `npm run build` instead?

**Comment by erezsh** [comment]
Okay, you're right, it doesn't work in a fresh build. I pushed the packages lock file, which should solve it.

Delete your node_modules and checkout the `dev` branch. Then run try again.

**Comment by tolatolatop** [comment]
Sorry, something is wrong. I missed the last message

**Comment by erezsh** [comment]
Just start with a new clone, and then do

```bash
git checkout dev
npm install
npm run dev
```

it should work.

**Comment by tolatolatop** [comment]
Unfortunately this doesn't seem to work for me.
````
root@vagrant:~/ide# git checkout dev
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
root@vagrant:~/ide# ls
build  package.json  package-lock.json  README.md  src  static  svelte.config.js  tsconfig.json
root@vagrant:~/ide# npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

added 211 packages, and audited 212 packages in 28s

30 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 8.1.4 -> 8.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.2.0
npm notice Run npm install -g npm@8.2.0 to update!
npm notice
root@vagrant:~/ide# npm run dev

> lark-ide@0.0.1 dev
> svelte-kit dev


  SvelteKit v1.0.0-next.142

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


12:19:27 PM [vite-plugin-svelte] /root/ide/src/routes/__layout.svelte:34:3 A11y: <a> element should have an href attribute
^C
root@vagrant:~/ide#
````
Some information on page source.
````
<header class="s-PoaHcXV6SIWL"><nav class="s-PoaHcXV6SIWL"><div id="home" class="s-PoaHcXV6SIWL"><a class="s-PoaHcXV6SIWL"><img src="lark-logo.png" alt="lark logo" class="s-PoaHcXV6SIWL"></a>
        <a href="https://lark-parser.readthedocs.io/en/latest/" target="_blank" class="s-PoaHcXV6SIWL">docs</a>
        <a href="https://github.com/lark-parser/ide" target="_blank" class="s-PoaHcXV6SIWL">source</a>
        <a href="https://github.com/lark-parser/lark" target="_blank" class="s-PoaHcXV6SIWL">parser</a></div>
<div id="title" class="s-PoaHcXV6SIWL">Parser IDE
</div>
<div id="right-panel" class="s-PoaHcXV6SIWL"><button class="button is-text s-PoaHcXV6SIWL">full screen</button></div></nav></header>

<main class="s-PoaHcXV6SIWL"><h1>404</h1>

<pre>Not found: /ide</pre>




<pre>Error: Not found: /ide
    at resolve (file:///root/ide/node_modules/@sveltejs/kit/dist/ssr.js:1644:13)
    at async Object.handle (/root/ide/src/hooks.ts:14:24)
    at async respond (file:///root/ide/node_modules/@sveltejs/kit/dist/ssr.js:1588:10)
    at async Immediate.&lt;anonymous&gt; (file:///root/ide/node_modules/@sveltejs/kit/dist/chunks/index.js:3458:22)</pre></main>

<footer class="s-PoaHcXV6SIWL"></footer>
````

**Comment by erezsh** [comment]
I just used a fresh clone and everything works. 

Pasting everything as-is:

```bash
PS C:\code\tmp> git clone https://github.com/lark-parser/ide.git
Cloning into 'ide'...
remote: Counting objects: 100% (345/345), done.
remote: Compressing objects: 100% (268/268), done.
remote: Total 345 (delta 148), reused 242 (delta 60), pack-reused 0
Receiving objects: 100% (345/345), 370.91 KiB | 98.00 KiB/s, done.
Resolving deltas: 100% (148/148), done.
PS C:\code\tmp> cd ide
PS C:\code\tmp\ide> git checkout dev
Switched to a new branch 'dev'
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
PS C:\code\tmp\ide> npm i
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

added 211 packages, and audited 212 packages in 8s

30 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
PS C:\code\tmp\ide> npm run dev

> lark-ide@0.0.1 dev
> svelte-kit dev


  SvelteKit v1.0.0-next.142

  network: not exposed
  local:   http://localhost:3000

  Use --host to expose server to other devices on this network


2:41:44 PM [vite-plugin-svelte] C:/code/tmp/ide/src/routes/__layout.svelte:34:3 A11y: <a> element should have an href attribute
2:41:44 PM [vite-plugin-svelte] C:/code/tmp/ide/src/routes/index.svelte:135:14 A11y: '#' is not a valid href attribute
2:41:44 PM [vite-plugin-svelte] C:/code/tmp/ide/src/routes/index.svelte:241:1 Unused CSS selector "#load-grammar select"
2:41:45 PM [vite-plugin-svelte] C:/code/tmp/ide/src/routes/__layout.svelte:34:3 A11y: <a> element should have an href attribute
2:41:45 PM [vite-plugin-svelte] C:/code/tmp/ide/src/routes/index.svelte:135:14 A11y: '#' is not a valid href attribute
2:41:45 PM [vite-plugin-svelte] C:/code/tmp/ide/src/routes/index.svelte:241:1 Unused CSS selector "#load-grammar select"

```

**Comment by erezsh** [comment]
> node --version
v16.13.1
> npm --version
8.1.2

**Comment by tolatolatop** [comment]
Exciting, I fixed the problem by modifying svelte.config.js
````javascript
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
        // Consult https://github.com/sveltejs/svelte-preprocess
        // for more information about preprocessors
        preprocess: preprocess(),

        kit: {
                // hydrate the <div id="svelte"> element in src/app.html
                target: '#svelte',
                adapter: adapter({}),
                paths: {
                        base: ''
                       // change 'ide'-> ' '
                },
        }
};
````
I noticed an abnormality in /root/ide/build/index.html when build it with `npm run build`.
````
                <link rel="modulepreload" href="/ide/_app/start-558aabb3.js">
                <link rel="modulepreload" href="/ide/_app/chunks/vendor-4228eee9.js">
                <link rel="modulepreload" href="/ide/_app/pages/__layout.svelte-ff030abb.js">
                <link rel="modulepreload" href="/ide/_app/pages/index.svelte-2b9be5f5.js">
                <link rel="stylesheet" href="/ide/_app/assets/start-a8cd1609.css">
                <link rel="stylesheet" href="/ide/_app/assets/pages/__layout.svelte-2148e0fe.css">
                <link rel="stylesheet" href="/ide/_app/assets/pages/index.svelte-2a34c484.css">
````

Thanks for your help.

**Comment by erezsh** [comment]
> Exciting, I fixed the problem by modifying svelte.config.js

That's great! Sorry I couldn't be more helpful.

**Comment by erezsh** [comment]
Should we close this issue?

**Comment by tolatolatop** [comment]
Okay.
